#!/bin/sh

# Random execution...

# Generate a random number between 1 and 100.
random_number=$(awk 'BEGIN{srand(); print int(100*rand())}')

# Check if the random number falls within the 2% range
if [ "$random_number" -le 2 ]; then
    $@
fi
